### ISSUE TITLE
Cant import posts

### ISSUE THREAD

**Issue by PrestaSafe** [klyp/october-wp-importer#4]
Hello, thanks for the plugin but i have an issue. 
I've tried to import wordpress posts but i have this error: 

```
"Call to a member function getContents() on integer" on line 145 of /Users/guillaume/Sites/october/plugins/klyp/wpimporter/models/Wpimporter.php
```

Do you have un idea ? 

Thanks !

**Comment by ARH-Digital** [comment]
This was fixed some time ago. Apparently it wasn't updated on the October plugin store though for some reason.

If you have access to your source code, please go to the file mentioned in that error, and change line 145 from 
``` $importFileContent = $this->import_xml_file->getContents(); ``` 
to
``` $importFileContent = $this->import_xml_file()->withDeferred(input('_session_key'))->first()->getContents(); ```

This should resolve the error.

**Comment by PrestaSafe** [comment]
Yes it works ! thanks a lot ! have you contact october support for fixing that ? because this plugin is very great !! Thanks again
